# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUI(object):
    def setupUi(self, JarvisUI):
        JarvisUI.setObjectName("JarvisUI")
        JarvisUI.resize(1130, 831)
        self.centralwidget = QtWidgets.QWidget(JarvisUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -10, 1141, 851))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(r"C:\\Users\\Asus\\Desktop\\Jarvis\\Gui_jarvis\\Black_Template.jpg")) #r converts normal string to raw string ,refer stack overflow
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(630, 40, 551, 391))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(r"C:\\Users\\Asus\\Desktop\\Jarvis\\Gui_jarvis\\Iron_Template_1.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, -30, 451, 301))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(r"C:\\Users\\Asus\\Desktop\\Jarvis\\Gui_jarvis\\initial.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-140, 400, 611, 471))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(r"C:\\Users\\Asus\\Desktop\\Jarvis\\Gui_jarvis\\Siri_1.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(710, 440, 381, 341))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(r"C:\\Users\\Asus\\Desktop\\Jarvis\\Gui_jarvis\\Code_Template.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(190, 230, 381, 241))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(r"C:\\Users\\Asus\\Desktop\\Jarvis\\Gui_jarvis\\Earth_Template.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 710, 131, 61))
        self.pushButton.setStyleSheet("font: 81 14pt \"Karla ExtraBold\";\n"
"border-color: rgb(31, 224, 234);\n"
"background-color: rgb(25, 144, 170);\n"
"color: rgb(35, 35, 35);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 710, 131, 61))
        self.pushButton_2.setStyleSheet("font: 81 14pt \"Karla ExtraBold\";\n"
"border-color: rgb(31, 224, 234);\n"
"background-color: rgb(25, 144, 170);\n"
"color: rgb(35, 35, 35);")
        self.pushButton_2.setObjectName("pushButton_2")
        JarvisUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisUI)
        QtCore.QMetaObject.connectSlotsByName(JarvisUI)

    def retranslateUi(self, JarvisUI):
        _translate = QtCore.QCoreApplication.translate
        JarvisUI.setWindowTitle(_translate("JarvisUI", "MainWindow"))
        self.pushButton.setText(_translate("JarvisUI", "START"))
        self.pushButton_2.setText(_translate("JarvisUI", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUI = QtWidgets.QMainWindow()
    ui = Ui_JarvisUI()
    ui.setupUi(JarvisUI)
    JarvisUI.show()
    sys.exit(app.exec_())
